### ISSUE TITLE
Error - secret key is missing in the configuration

### ISSUE THREAD

**Issue by martinduplex** [cronfig/mautic-cronfig#2]
When I created and run 3 cron tasks in Cronfig in Mautic (after logging in with API key provided in the start of the installation), and after time of waiting, one of cron tasks for Update segments comes with error "HTTP status is not 2xx. That means not successful."

The following is the message in detail in regard to job:

**Job output**
error: secret key is missing in the configuration

**Job request headers**
{
	"x-powered-by": "PHP/5.6.28",
	"set-cookie": [
		"d85b2cde93c7de4492148b574331b6b4=v2k1ahgludhm2c5nksnm3ad5i5; path=/; HttpOnly"
	],
	"cache-control": "no-cache",
	"content-type": "text/plain; charset=UTF-8",
	"content-length": "49",
	"date": "Wed, 14 Dec 2016 06:54:06 GMT",
	"accept-ranges": "bytes",
	"server": "LiteSpeed",
	"connection": "Keep-Alive"
}

I am assuming this Cronfig plugin is still in beta stage? And where we have to put the secret key in the configuration?

Thanks in advance for any suggestions to rectify this error.

**Comment by apuestaya** [comment]
Hi, any fix for this meesage?
thank you in advance

**Comment by escopecz** [comment]
Hi guys, thanks for the report. I'll try to look at it soon. Although my time is limited. If you have any developer at your disposal, ask him for a fix and a pull request. This plugin is open source.

**Comment by Paul979** [comment]
I'm having this issue also

**Comment by apuestaya** [comment]
Hi @Paul979 i finally fixed that issue and it is working great right now. I don't remember howi fixed that but i can fix it for you if youpay for my development service. I can show you mautic working on my server.

**Comment by Paul979** [comment]
@apuestaya Can't you just tell the people here how you fixed it for the benefit of everyone? Or at least the direction to look in

I'm comfortable with code. And if it's a server issue I prefer not to give out my credentials, but I'm sure the hosting support will be able to help me with it - if they know in which direction to look.

I'm now running this script for my crons, which works without a hitch: https://gist.github.com/ChgoChad/fe9950c628ad8169cd27a58ee64106e8

But it would be good to have a fix for this also, just in case that script gets outdated and stops working. Then at least I'll have a backup.

**Comment by escopecz** [comment]
Upgrade the plugin's files at `plugins/CronfigBundle/` with files in the latest version of the plugin. like this:

1. Download the Zip file with the latest files can be downloaded from https://github.com/cronfig/mautic-cronfig/archive/master.zip
2. Clear Mautic's cache by deleting the content of `app/cache`.
3. Refresh your browser.
4. Delete all your current jobs.
5. Log out from Cronfig.
6. Log back in.
7. Create the jobs again.

Let me know if the problem is solved for you, please.

**Comment by escopecz** [comment]
I just found another reason why it's not matching the key:

```
mautic.ERROR: Cronfig: secret key mismatch: 88...19 != 88...19?error_count=3 [] []
```
Just putting it here for myself.

**Comment by escopecz** [comment]
Should be fixed.

**Comment by martinduplex** [comment]
Hi @escopecz 

The issue still persisted and appeared to show http 2xx error only for "Update Segment" cron job. I have attached screenshot as proof. https://ibb.co/ixOroQ

Any suggestions?

Thanks,

**Comment by escopecz** [comment]
That's not the error discussed in this issue. This issue is about this error:

> secret key is missing in the configuration

Which should be fixed now.

Your error is

> Script in progress

Which is actually not an error. Mautic is just saying that it won't run the script again until the previous finishes. The Mautic-Cronfig plugin will use the `--force` parameter after it fails for 4 times in a row because it could also happen if an error occurs during the script execution. You'd see that error in the Mautic logs.
